# Generated by Django 3.2.25 on 2025-02-08 11:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250205_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='models',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
